package com.eclassroom.core.grading;

import com.eclassroom.core.identity.AccessService;
import com.eclassroom.core.notification.NotificationService;
import com.eclassroom.core.shared.api.ApiException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class GradingService {
    private final JdbcTemplate jdbc;private final AccessService access;private final NotificationService notifications;
    public GradingService(JdbcTemplate jdbc,AccessService access,NotificationService notifications){this.jdbc=jdbc;this.access=access;this.notifications=notifications;}
    @Transactional public UUID create(UUID schoolId,UUID assignmentId,UUID semesterId,String title,String category,BigDecimal max,BigDecimal weight,LocalDate date,UUID actor){access.requireTeacherAssignment(schoolId,actor,assignmentId);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO grading.assessments(id,school_id,teaching_assignment_id,semester_id,title,category,max_score,weight,assessment_date,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)",id,schoolId,assignmentId,semesterId,title,category,max,weight,date,actor);return id;}
    @Transactional public void saveScores(UUID assessmentId,List<ScoreInput> scores,String reason,UUID actor){Map<String,Object>a=assessment(assessmentId);UUID schoolId=(UUID)a.get("school_id"),assignmentId=(UUID)a.get("teaching_assignment_id");access.requireTeacherAssignment(schoolId,actor,assignmentId);if("LOCKED".equals(a.get("status")))throw ApiException.conflict("ASSESSMENT_LOCKED","Assessment is locked");BigDecimal max=(BigDecimal)a.get("max_score");UUID classroomId=jdbc.queryForObject("SELECT classroom_id FROM academic.teaching_assignments WHERE id=?",UUID.class,assignmentId);
        for(ScoreInput s:scores){if(s.score().compareTo(BigDecimal.ZERO)<0||s.score().compareTo(max)>0)throw ApiException.badRequest("INVALID_SCORE","Score outside assessment range");Integer enrolled=jdbc.queryForObject("SELECT COUNT(*) FROM academic.class_enrollments WHERE school_id=? AND classroom_id=? AND student_id=? AND status='ACTIVE'",Integer.class,schoolId,classroomId,s.studentId());if(enrolled==null||enrolled==0)throw ApiException.badRequest("STUDENT_NOT_ENROLLED","Student not in assessment classroom");List<Map<String,Object>> old=jdbc.queryForList("SELECT id,score FROM grading.student_scores WHERE assessment_id=? AND student_id=?",assessmentId,s.studentId());UUID scoreId=old.isEmpty()?UUID.randomUUID():(UUID)old.getFirst().get("id");BigDecimal previous=old.isEmpty()?null:(BigDecimal)old.getFirst().get("score");jdbc.update("INSERT INTO grading.student_scores(id,school_id,assessment_id,student_id,score,recorded_by) VALUES (?,?,?,?,?,?) ON CONFLICT(assessment_id,student_id) DO UPDATE SET score=EXCLUDED.score,recorded_by=EXCLUDED.recorded_by,updated_at=NOW(),version=grading.student_scores.version+1",scoreId,schoolId,assessmentId,s.studentId(),s.score(),actor);if(previous==null||previous.compareTo(s.score())!=0)jdbc.update("INSERT INTO grading.score_revisions(id,school_id,student_score_id,previous_score,new_score,actor_user_id,reason) VALUES (?,?,?,?,?,?,?)",UUID.randomUUID(),schoolId,scoreId,previous,s.score(),actor,reason);}}
    @Transactional public void submit(UUID assessmentId,UUID actor){Map<String,Object>a=assessment(assessmentId);UUID schoolId=(UUID)a.get("school_id"),assignmentId=(UUID)a.get("teaching_assignment_id");access.requireTeacherAssignment(schoolId,actor,assignmentId);if("LOCKED".equals(a.get("status")))throw ApiException.conflict("ASSESSMENT_LOCKED","Assessment is locked");jdbc.update("UPDATE grading.assessments SET status='SUBMITTED' WHERE id=?",assessmentId);jdbc.update("UPDATE grading.student_scores SET status='SUBMITTED' WHERE assessment_id=?",assessmentId);List<Map<String,Object>> rows=jdbc.queryForList("SELECT ss.student_id,ss.score,s.full_name FROM grading.student_scores ss JOIN academic.students s ON s.id=ss.student_id WHERE ss.assessment_id=?",assessmentId);for(Map<String,Object> r:rows)notifications.notifyGuardians(schoolId,(UUID)r.get("student_id"),"student.score.changed","New score: "+a.get("title"),r.get("full_name")+" received "+r.get("score")+" / "+a.get("max_score"),"ASSESSMENT",assessmentId);}
    @Transactional public void lock(UUID id,UUID actor){Map<String,Object>a=assessment(id);access.requireAnyRole((UUID)a.get("school_id"),actor,"SCHOOL_ADMIN");jdbc.update("UPDATE grading.assessments SET status='LOCKED' WHERE id=?",id);jdbc.update("UPDATE grading.student_scores SET status='LOCKED' WHERE assessment_id=?",id);}
    public List<Map<String,Object>> scores(UUID schoolId,UUID studentId,UUID actor){access.requireStudentView(schoolId,actor,studentId);return jdbc.queryForList("SELECT a.id assessment_id,a.title,a.category,a.max_score,a.weight,a.assessment_date,a.status,ss.score,sub.name subject_name,ss.updated_at FROM grading.student_scores ss JOIN grading.assessments a ON a.id=ss.assessment_id JOIN academic.teaching_assignments ta ON ta.id=a.teaching_assignment_id JOIN academic.subjects sub ON sub.id=ta.subject_id WHERE ss.school_id=? AND ss.student_id=? ORDER BY a.assessment_date DESC NULLS LAST,a.created_at DESC",schoolId,studentId);}
    public List<Map<String,Object>> byAssignment(UUID schoolId,UUID assignmentId,UUID actor){access.requireTeacherAssignment(schoolId,actor,assignmentId);return jdbc.queryForList("SELECT a.*,COUNT(ss.id) score_count FROM grading.assessments a LEFT JOIN grading.student_scores ss ON ss.assessment_id=a.id WHERE a.school_id=? AND a.teaching_assignment_id=? GROUP BY a.id ORDER BY a.created_at DESC",schoolId,assignmentId);}
    private Map<String,Object> assessment(UUID id){List<Map<String,Object>>l=jdbc.queryForList("SELECT * FROM grading.assessments WHERE id=?",id);if(l.isEmpty())throw ApiException.notFound("Assessment not found");return l.getFirst();}
    public record ScoreInput(UUID studentId,BigDecimal score){}
}
