export type TokenResponse={accessToken:string;refreshToken:string;expiresAt:string;tokenType:string;mustChangePassword?:boolean}
const ACCESS='eclassroom.access',REFRESH='eclassroom.refresh'
export const tokens={access:()=>localStorage.getItem(ACCESS),refresh:()=>localStorage.getItem(REFRESH),set:(t:TokenResponse)=>{localStorage.setItem(ACCESS,t.accessToken);localStorage.setItem(REFRESH,t.refreshToken)},clear:()=>{localStorage.removeItem(ACCESS);localStorage.removeItem(REFRESH)}}

export class ApiError extends Error{constructor(public status:number,public code:string,message:string){super(message)}}

async function parseError(response:Response){let message=`HTTP ${response.status}`,code='HTTP_ERROR';try{const body=await response.json() as {message?:string;code?:string};message=body.message||message;code=body.code||code}catch{}return new ApiError(response.status,code,message)}
async function refreshToken(){const refreshToken=tokens.refresh();if(!refreshToken)throw new ApiError(401,'SESSION_EXPIRED','Session expired');const r=await fetch('/api/v1/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})});if(!r.ok)throw new ApiError(401,'SESSION_EXPIRED','Session expired');const t=await r.json() as TokenResponse;tokens.set(t);return t.accessToken}
export async function api<T=unknown>(path:string,init:RequestInit={},retry=true):Promise<T>{let access=tokens.access();const headers=new Headers(init.headers);if(access)headers.set('Authorization',`Bearer ${access}`);if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');let r=await fetch(path,{...init,headers});if(r.status===401&&retry&&tokens.refresh()){try{access=await refreshToken();headers.set('Authorization',`Bearer ${access}`);r=await fetch(path,{...init,headers})}catch{tokens.clear();throw new ApiError(401,'SESSION_EXPIRED','Phiên đăng nhập đã hết hạn')}}if(!r.ok)throw await parseError(r);if(r.status===204)return undefined as T;const text=await r.text();return(text?JSON.parse(text):undefined)as T}
export async function login(email:string,password:string){const r=await fetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw new ApiError(r.status,'INVALID_CREDENTIALS','Email hoặc mật khẩu không đúng');const t=await r.json() as TokenResponse;tokens.set(t);return t}
export async function logout(){const refreshToken=tokens.refresh();try{await fetch('/api/v1/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})})}finally{tokens.clear()}}
