package com.eclassroom.core.communication;

import com.eclassroom.core.identity.AccessService;
import com.eclassroom.core.notification.NotificationService;
import com.eclassroom.core.shared.api.ApiException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;import java.util.List;import java.util.Map;import java.util.UUID;

@Service
public class CommunicationService {
    private final JdbcTemplate jdbc;private final AccessService access;private final NotificationService notifications;
    public CommunicationService(JdbcTemplate jdbc,AccessService access,NotificationService notifications){this.jdbc=jdbc;this.access=access;this.notifications=notifications;}
    @Transactional public UUID announce(UUID schoolId,String title,String body,String targetType,UUID targetId,UUID actor){
        if("SCHOOL".equals(targetType))access.requireAnyRole(schoolId,actor,"SCHOOL_ADMIN");else if("CLASSROOM".equals(targetType)){if(targetId==null)throw ApiException.badRequest("TARGET_REQUIRED","Classroom target is required");access.requireClassTeacherOrAdmin(schoolId,actor,targetId);}else throw ApiException.badRequest("INVALID_TARGET","Target must be SCHOOL or CLASSROOM");
        UUID id=UUID.randomUUID();jdbc.update("INSERT INTO communication.announcements(id,school_id,title,body,target_type,target_id,published_by) VALUES (?,?,?,?,?,?,?)",id,schoolId,title,body,targetType,targetId,actor);List<UUID> recipients=recipients(schoolId,targetType,targetId);notifications.notifyUsers(schoolId,recipients,"announcement.published",title,body,"ANNOUNCEMENT",id);return id;
    }
    public List<Map<String,Object>> announcements(UUID schoolId,UUID userId){access.requireMembership(schoolId,userId);return jdbc.queryForList("SELECT a.* FROM communication.announcements a WHERE a.school_id=? AND (a.target_type='SCHOOL' OR (a.target_type='CLASSROOM' AND a.target_id IN (SELECT e.classroom_id FROM academic.class_enrollments e JOIN academic.students s ON s.id=e.student_id WHERE e.status='ACTIVE' AND s.user_id=? UNION SELECT e.classroom_id FROM academic.class_enrollments e JOIN academic.student_guardians sg ON sg.student_id=e.student_id JOIN academic.guardians g ON g.id=sg.guardian_id WHERE e.status='ACTIVE' AND g.user_id=? UNION SELECT ta.classroom_id FROM academic.teaching_assignments ta JOIN academic.teachers t ON t.id=ta.teacher_id WHERE ta.status='ACTIVE' AND t.user_id=?))) ORDER BY a.published_at DESC",schoolId,userId,userId,userId);}
    @Transactional public UUID comment(UUID schoolId,UUID studentId,String body,String visibility,UUID actor){access.requireTeacherOfStudentOrAdmin(schoolId,actor,studentId);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO communication.teacher_comments(id,school_id,student_id,teacher_user_id,body,visibility) VALUES (?,?,?,?,?,?)",id,schoolId,studentId,actor,body,visibility);if(!"PRIVATE".equals(visibility))notifications.notifyGuardians(schoolId,studentId,"teacher-comment.created","New teacher comment",body,"TEACHER_COMMENT",id);return id;}
    public List<Map<String,Object>> comments(UUID schoolId,UUID studentId,UUID actor){access.requireStudentView(schoolId,actor,studentId);return jdbc.queryForList("SELECT c.*,u.full_name teacher_name FROM communication.teacher_comments c JOIN identity.users u ON u.id=c.teacher_user_id WHERE c.school_id=? AND c.student_id=? AND c.visibility<>'PRIVATE' ORDER BY c.created_at DESC",schoolId,studentId);}
    @Transactional public UUID conversation(UUID schoolId,String subject,List<UUID> participantIds,UUID actor){access.requireMembership(schoolId,actor);List<UUID> all=new ArrayList<>(participantIds==null?List.of():participantIds);if(!all.contains(actor))all.add(actor);for(UUID user:all){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM identity.school_memberships WHERE school_id=? AND user_id=? AND status='ACTIVE'",Integer.class,schoolId,user);if(n==null||n==0)throw ApiException.badRequest("INVALID_PARTICIPANT","Conversation participant is not a school member");}UUID id=UUID.randomUUID();jdbc.update("INSERT INTO communication.conversations(id,school_id,subject,created_by) VALUES (?,?,?,?)",id,schoolId,subject,actor);for(UUID user:all)jdbc.update("INSERT INTO communication.conversation_participants(conversation_id,user_id) VALUES (?,?)",id,user);return id;}
    public List<Map<String,Object>> conversations(UUID schoolId,UUID userId){access.requireMembership(schoolId,userId);return jdbc.queryForList("SELECT c.id,c.subject,c.created_at,(SELECT body FROM communication.messages m WHERE m.conversation_id=c.id ORDER BY m.created_at DESC LIMIT 1) last_message FROM communication.conversations c JOIN communication.conversation_participants p ON p.conversation_id=c.id WHERE c.school_id=? AND p.user_id=? ORDER BY COALESCE((SELECT MAX(created_at) FROM communication.messages m WHERE m.conversation_id=c.id),c.created_at) DESC",schoolId,userId);}
    public List<Map<String,Object>> messages(UUID conversationId,UUID userId){requireParticipant(conversationId,userId);return jdbc.queryForList("SELECT m.id,m.sender_user_id,u.full_name sender_name,m.body,m.created_at FROM communication.messages m JOIN identity.users u ON u.id=m.sender_user_id WHERE m.conversation_id=? ORDER BY m.created_at",conversationId);}
    @Transactional public UUID send(UUID conversationId,String body,UUID userId){Map<String,Object> c=requireParticipant(conversationId,userId);UUID id=UUID.randomUUID();jdbc.update("INSERT INTO communication.messages(id,conversation_id,sender_user_id,body) VALUES (?,?,?,?)",id,conversationId,userId,body);List<UUID> recipients=jdbc.query("SELECT user_id FROM communication.conversation_participants WHERE conversation_id=? AND user_id<>?",(rs,i)->UUID.fromString(rs.getString(1)),conversationId,userId);notifications.notifyUsers((UUID)c.get("school_id"),recipients,"message.created","New message",body,"CONVERSATION",conversationId);return id;}
    private Map<String,Object> requireParticipant(UUID conversationId,UUID userId){List<Map<String,Object>> rows=jdbc.queryForList("SELECT c.* FROM communication.conversations c JOIN communication.conversation_participants p ON p.conversation_id=c.id WHERE c.id=? AND p.user_id=?",conversationId,userId);if(rows.isEmpty())throw ApiException.forbidden("Not a conversation participant");return rows.getFirst();}
    private List<UUID> recipients(UUID schoolId,String type,UUID targetId){if("SCHOOL".equals(type))return jdbc.query("SELECT DISTINCT user_id FROM identity.school_memberships WHERE school_id=? AND status='ACTIVE'",(rs,i)->UUID.fromString(rs.getString(1)),schoolId);return jdbc.query("SELECT DISTINCT user_id FROM (SELECT s.user_id FROM academic.class_enrollments e JOIN academic.students s ON s.id=e.student_id WHERE e.classroom_id=? AND e.status='ACTIVE' AND s.user_id IS NOT NULL UNION SELECT g.user_id FROM academic.class_enrollments e JOIN academic.student_guardians sg ON sg.student_id=e.student_id JOIN academic.guardians g ON g.id=sg.guardian_id WHERE e.classroom_id=? AND e.status='ACTIVE' AND g.user_id IS NOT NULL UNION SELECT t.user_id FROM academic.teaching_assignments ta JOIN academic.teachers t ON t.id=ta.teacher_id WHERE ta.classroom_id=? AND ta.status='ACTIVE' AND t.user_id IS NOT NULL) x",(rs,i)->UUID.fromString(rs.getString(1)),targetId,targetId,targetId);}
}
