package com.eclassroom.core.reporting;

import com.eclassroom.core.identity.AccessService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import java.util.LinkedHashMap;import java.util.List;import java.util.Map;import java.util.UUID;

@Service
public class ReportingService {
    private final JdbcTemplate jdbc;private final AccessService access;public ReportingService(JdbcTemplate jdbc,AccessService access){this.jdbc=jdbc;this.access=access;}
    public Map<String,Object> school(UUID schoolId,UUID actor){access.requireAnyRole(schoolId,actor,"SCHOOL_ADMIN","TEACHER");Map<String,Object> out=new LinkedHashMap<>();out.put("students",count("academic.students",schoolId));out.put("teachers",count("academic.teachers",schoolId));out.put("classrooms",count("academic.classrooms",schoolId));out.put("attendance",jdbc.queryForMap("SELECT COUNT(*) total,COUNT(*) FILTER(WHERE status='PRESENT') present,COUNT(*) FILTER(WHERE status='ABSENT') absent,COUNT(*) FILTER(WHERE status='LATE') late FROM attendance.records WHERE school_id=?",schoolId));out.put("averageScore",jdbc.queryForObject("SELECT COALESCE(ROUND(AVG(score),2),0) FROM grading.student_scores WHERE school_id=? AND status IN ('SUBMITTED','LOCKED')",java.math.BigDecimal.class,schoolId));out.put("recentAbsences",jdbc.queryForList("SELECT st.id student_id,st.full_name,s.attendance_date,s.period,sub.name subject_name FROM attendance.records r JOIN attendance.sessions s ON s.id=r.attendance_session_id JOIN academic.students st ON st.id=r.student_id JOIN academic.teaching_assignments ta ON ta.id=s.teaching_assignment_id JOIN academic.subjects sub ON sub.id=ta.subject_id WHERE r.school_id=? AND r.status='ABSENT' ORDER BY s.attendance_date DESC,r.marked_at DESC LIMIT 20",schoolId));return out;}
    public Map<String,Object> student(UUID schoolId,UUID studentId,UUID actor){access.requireStudentView(schoolId,actor,studentId);Map<String,Object> out=new LinkedHashMap<>();out.put("student",jdbc.queryForMap("SELECT id,student_code,full_name,date_of_birth,gender,status FROM academic.students WHERE school_id=? AND id=?",schoolId,studentId));out.put("attendanceSummary",jdbc.queryForList("SELECT status,COUNT(*) count FROM attendance.records WHERE school_id=? AND student_id=? GROUP BY status ORDER BY status",schoolId,studentId));out.put("subjectAverages",jdbc.queryForList("SELECT sub.id subject_id,sub.name subject_name,ROUND(SUM(ss.score*a.weight)/NULLIF(SUM(a.weight),0),2) weighted_average FROM grading.student_scores ss JOIN grading.assessments a ON a.id=ss.assessment_id JOIN academic.teaching_assignments ta ON ta.id=a.teaching_assignment_id JOIN academic.subjects sub ON sub.id=ta.subject_id WHERE ss.school_id=? AND ss.student_id=? AND ss.status IN ('SUBMITTED','LOCKED') GROUP BY sub.id,sub.name ORDER BY sub.name",schoolId,studentId));out.put("risk",riskFor(studentId));return out;}
    public List<Map<String,Object>> risks(UUID schoolId,UUID actor){access.requireAnyRole(schoolId,actor,"SCHOOL_ADMIN","TEACHER");return jdbc.queryForList("WITH a AS (SELECT student_id,COUNT(*) total,COUNT(*) FILTER(WHERE status='ABSENT') absent FROM attendance.records WHERE school_id=? GROUP BY student_id),g AS (SELECT student_id,AVG(score) avg_score FROM grading.student_scores WHERE school_id=? AND status IN ('SUBMITTED','LOCKED') GROUP BY student_id) SELECT s.id student_id,s.full_name,COALESCE(a.total,0) attendance_total,COALESCE(a.absent,0) absent_count,ROUND(CASE WHEN COALESCE(a.total,0)=0 THEN 0 ELSE a.absent::numeric/a.total*100 END,1) absence_percent,ROUND(COALESCE(g.avg_score,0),2) average_score,CASE WHEN (COALESCE(a.total,0)>=5 AND a.absent::numeric/a.total>=0.2) OR (g.avg_score IS NOT NULL AND g.avg_score<5) THEN 'HIGH' WHEN (COALESCE(a.total,0)>=5 AND a.absent::numeric/a.total>=0.1) OR (g.avg_score IS NOT NULL AND g.avg_score<6.5) THEN 'MEDIUM' ELSE 'LOW' END risk_level FROM academic.students s LEFT JOIN a ON a.student_id=s.id LEFT JOIN g ON g.student_id=s.id WHERE s.school_id=? ORDER BY CASE WHEN (COALESCE(a.total,0)>=5 AND a.absent::numeric/a.total>=0.2) OR (g.avg_score IS NOT NULL AND g.avg_score<5) THEN 0 WHEN (COALESCE(a.total,0)>=5 AND a.absent::numeric/a.total>=0.1) OR (g.avg_score IS NOT NULL AND g.avg_score<6.5) THEN 1 ELSE 2 END,s.full_name",schoolId,schoolId,schoolId);}
    private long count(String table,UUID schoolId){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE school_id=?",Long.class,schoolId);return n==null?0:n;}
    private Map<String,Object> riskFor(UUID studentId){Map<String,Object>a=jdbc.queryForMap("SELECT COUNT(*) total,COUNT(*) FILTER(WHERE status='ABSENT') absent FROM attendance.records WHERE student_id=?",studentId);java.math.BigDecimal avg=jdbc.queryForObject("SELECT COALESCE(AVG(score),0) FROM grading.student_scores WHERE student_id=? AND status IN ('SUBMITTED','LOCKED')",java.math.BigDecimal.class,studentId);long total=((Number)a.get("total")).longValue(),absent=((Number)a.get("absent")).longValue();double rate=total==0?0:(double)absent/total;String level=(total>=5&&rate>=.2)||(avg!=null&&avg.doubleValue()>0&&avg.doubleValue()<5)?"HIGH":(total>=5&&rate>=.1)||(avg!=null&&avg.doubleValue()>0&&avg.doubleValue()<6.5)?"MEDIUM":"LOW";return Map.of("level",level,"absenceRate",rate,"averageScore",avg==null?0:avg);}
}
